### ISSUE TITLE
Move TimeSavers context menu item off the top

### ISSUE THREAD

**Issue by justcla** [luminous-software/time-savers#2]
Please move TimeSavers somewhere lower in the context menu so I can access QuickActions as the top item on the editor context menu.

I suggest moving it to the bottom. Bottom is the next easiest place to access.

**Comment by yannduran** [comment]
We've already had a lengthy discussion about this offline. In addition, just as with the discussion about the *Time Savers* menu, other extensions can, and do, take the top spot. 

I can't agree with you about the bottom being the easiest to access. If it was then the *Quick Actions and Refactoring* item would be on the bottom :-P

Besides, as the context menu gets longer and longer, it gets increasingly difficult to find anything. That's exactly why the menu was added, instead of adding all of the commands directly in the context menu, even though it added an extra keystroke which I would have liked to avoid.

I thought that adding a menu was the responsible thing to do and was the best compromise.

**Comment by yannduran** [comment]
As we discussed offline, there's no justification for this move.
