### ISSUE TITLE
Move TimeSavers menu off the Main Menu

### ISSUE THREAD

**Issue by justcla** [luminous-software/time-savers#3]
Please move the TimeSavers menu item off the Main Menu as it clutters the top level space and re-uses the letter T for a keyboard accelerator, blocking me from going to the Tools menu.

My suggestion would be to move TimeSavers into the Tools menu.

**Comment by yannduran** [comment]
There's quite a number of precedents to have a company-specific or extension-specific menu on the menu bar, for easy access. [Resharper] is a good example. [Supercharger] is another that I have installed. [Favorites' is yet another one that I have installed that does this.

It was originally going to be a *Luminous* menu, so that all *Luminous Software* extensions could add to the **one** menu. But with *Time Savers*, the whole idea was **saving time**, and people **not** having to hunt through menus to find what they needed. For that reason, moving it into the *Tools* menu would basically defeat the purpose.

I'm not sure if I can actually add an option to display it or not, I'd have to check. But I just wanted to check with you first whether this was super important for you. I haven't had anyone else ever mention it being a problem. As I said, people tend to be used to it.

Let me know if you still think you absolutely need it removed and I'll see what I can do.

**Comment by justcla** [comment]
Agreed. Some extensions do put menu items on the main bar. But typically these are pretty large/important extensions. ReSharper is a good example. But as a general rule, we don't encourage every extension developer to add an item to the main menu. Only in cases where it is super critical/worthy of the main menu is it recommended.
I take the point that you want easy access to the commands in the menu, and putting them in a sub menu adds one extra step when activating the commands via mouse or keyboard accelerators. (Alt+[letter]). Allowing the commands to be assigned in the keyboard options is a great way to deliver fast keyboard accessibility. Have you given all the commands good command names that can be found in Tools->Options->Keyboard?

**Comment by justcla** [comment]
I see that other extensions do it quite frequently.
I feel this extension is just as worthy of a main menu item as any other.

So long as it doesn't hold a keyboard accelerator, then it should not affect user behavior other than adding width to the bar. Might as well leave it there.

**Comment by yannduran** [comment]
Also, I just checked, and ```Alt-T``` **still** brings up the *Tools* menu. The *Time Savers* menu currently has no accelerator key defined. You can check this for yourself, by pressing the ```Alt``` key by itself and you'll see each of the menus' accelerator keys underlined.

I might actually add an ```Alt-I``` accelerator key now that I realise that it would give people who prefer to use the keyboard over a mouse a quicker way to open the menu. That key combination is currently not  being used.

**Comment by justcla** [comment]
Then again, without a keyboard accelerator on it, how are you meant to access it quickly?

**Comment by justcla** [comment]
Chad Boles would be very upset if you took Alt+i. It's in Team Explorer for "Commit".

**Comment by justcla** [comment]
But I've submitted a pull request for Ctrl+Enter = Commit in Team Explorer, which should free up the Alt+i shortcut.

Edit: The pull request is still under consideration.

**Comment by yannduran** [comment]
That's a good point about ```Alt-I``` being used for *commit*. I wasn't aware of that one. I can hold off adding one. Adding a keyboard accelerator for *Time Savers* isn't a necessity anyway.

**Comment by justcla** [comment]
It would make it easier to access, which is kind of the point of TimeSavers. ;-)
